import { useEffect, useMemo, useState } from 'react';
import { fetchJson } from '../../shared/src/api';
import { socket } from '../../shared/src/socket';
import { statusSteps } from '../../shared/src/orderStatus';
export default function App() {
  const [menu, setMenu] = useState([]); const [cart, setCart] = useState([]); const [createdOrder, setCreatedOrder] = useState(null); const [orderType, setOrderType] = useState('sur_place'); const [tableNumber, setTableNumber] = useState('12');
  useEffect(() => { fetchJson('/api/menu').then(setMenu); }, []);
  useEffect(() => { const sync = (order) => { if (order.ref === createdOrder?.ref) setCreatedOrder(order); }; socket.on('order:update', sync); socket.on('order:ready', sync); socket.on('order:served', sync); return () => { socket.off('order:update', sync); socket.off('order:ready', sync); socket.off('order:served', sync); }; }, [createdOrder]);
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  function addToCart(item) { setCart((cur) => { const e = cur.find((x) => x.id === item.id); return e ? cur.map((x) => x.id === item.id ? { ...x, quantity: x.quantity + 1 } : x) : [...cur, { ...item, quantity: 1 }]; }); }
  async function submitOrder() { const payload = { orderType, tableNumber, total, paid: true, items: cart.map((i) => ({ menuItemId: i.id, name: i.name, quantity: i.quantity, unitPrice: i.price })) }; const order = await fetchJson('/api/orders', { method: 'POST', body: JSON.stringify(payload) }); setCreatedOrder(order); setCart([]); }
  return <main><header className="page-header"><div><h1>Client / Caisse</h1><p className="small">Prise de commande, paiement simulé et suivi temps réel.</p></div><span className="badge" style={{ background: '#dcfce7', color: '#166534' }}>Rôle client</span></header><div className="grid grid-2"><section className="card"><h2>Menu</h2><div className="grid">{menu.map((item) => <article key={item.id} className="card" style={{ padding: 16, boxShadow: 'none', border: '1px solid #eef2f7' }}><h3>{item.name}</h3><p className="small">{item.description}</p><strong>{item.price.toFixed(2)} €</strong><div style={{ marginTop: 12 }}><button className="primary" onClick={() => addToCart(item)}>Ajouter</button></div></article>)}</div></section><section className="card"><h2>Commande</h2><label>Type de commande</label><select value={orderType} onChange={(e) => setOrderType(e.target.value)}><option value="sur_place">Sur place</option><option value="emporter">À emporter</option></select><div style={{ height: 12 }} /><label>Table</label><input value={tableNumber} onChange={(e) => setTableNumber(e.target.value)} /><ul className="clean" style={{ marginTop: 20 }}>{cart.map((item) => <li key={item.id} className="order-row"><span>{item.name} × {item.quantity}</span><strong>{(item.price * item.quantity).toFixed(2)} €</strong></li>)}</ul><div className="order-row"><strong>Total</strong><strong>{total.toFixed(2)} €</strong></div><button className="primary" disabled={!cart.length} onClick={submitOrder}>Payer et valider</button></section></div>{createdOrder && <section className="card" style={{ marginTop: 20 }}><h2>Suivi de la commande {createdOrder.ref}</h2><div className="progress">{statusSteps.map((step) => <div key={step.key} className={`progress-step ${statusSteps.findIndex((s) => s.key === createdOrder.status) >= statusSteps.findIndex((s) => s.key === step.key) ? 'active' : ''}`}>{step.label}</div>)}</div></section>}</main>;
}
